services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app/app
      - ./uploads:/app/uploads
      - ./dev.db:/app/dev.db
    env_file:
      - .env
    dns:
      - 8.8.8.8
      - 8.8.4.4
