services:
  - type: web
    name: helpy
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.11
    healthCheckPath: /